### ISSUE TITLE
website is offline

### ISSUE THREAD

**Issue by ndelangen** [patmood/svg-jsx-online#1]
Hey 👋, the website seems to be unreachable

**Comment by patmood** [comment]
Thanks for the heads up! This tool is probably unnecessary now because I think newer versions of react support all SVG attributes.

I wasnt able to get the site working, but you could:

1. Clone this repo and try opening `index.html` in the `gh-pages` branch
2. Use the svg-to-jsx module directly at https://github.com/janjakubnanista/svg-to-jsx (which is all this site does)

I'll probably just delete this repo
